exports('showDialog', showDialog)
exports('closeDialog', closeDialog)
exports('getDialogState', getDialogState)
exports('isDialogOpen', getDialogState)
exports('stopAnimations', stopCurrentAnimations)
exports('openDialogById', openDialogById)
exports('setActivePed', setActivePed)
exports('getActivePed', getActivePed)
exports('createPedAndOpen', createPedAndOpen)
exports('registerTaskAction', registerTaskAction)

exports('playAnimation', playAnimation)
exports('playFacialAnimation', playFacialAnimation)
exports('getPresetAnimations', getPresetAnimations)
exports('getPresetFacials', getPresetFacials)
